version: '3.3'
services:
  webserver: 
    build:
      context: . 
      dockerfile: docker/dockerfile
    container_name: webserver
    ports: 
      - 9000:80
    volumes:
      - ./public:/usr/share/nginx/html

